language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.2
  - 2.4.1
  - 2.5.0
  - ruby-head
bundler_args: "--jobs=2"
cache: bundler
sudo: false
before_install:
  - gem update --system --no-document
  - gem install bundler -v 1.16.1 --no-document
before_script:
  - export CI=true
  - CODECLIMATE_REPO_TOKEN=cc1e362553ab62ebaeda2b14f077705753a92a2b8fb4e5b0a41cc597930ac240
script:
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter
branches:
  only:
    - master
notifications:
  email: false
  slack:
    secure: kSjrUG/Zz/QQU8+w+Nw10QHmqoSUSk/UwuCHKtW9bhFxqHBfKCmrDjWMpFSJv8lwl64XLlFAEvKFsCPAc7a1T6llFsPno/rMPcIMOzm06jegozLYcg2cY7kpFz+C5fKAWH1HgThj5+oOcHyA1ZbeWtwJoCeR6oT5zX8noiqPBif4OZlQYCHl61D3e+6ifP1NNvf5TCKj3mAUrTciSf6THAXUi1INupKe/ZwVAesuIwKWlY3mg5wN0KjLE4bOxCbnxM58ysj87dsQLnR+/CJsUh2t0J1BORUoatuMUulsct/Urv5Bj3455PNiEvQrt4rnr4rKaeBX5l1V0SSqnue9zbdRC0Repd7Xn5liRY3vTgX2yK7uFs6tHS4Xrcunn8eZL/Qhij694N2SBp62uRBK4aCmINf2lupZRhyRsFIJznPChhfxsY4kcy26LZ3GOhG0EE1DWwqWfzG+4rY5qKqP+ew1nvnI+xhbIbTrqthvEGbBZRspcHTIi7++104Z0dY8TX4Ca5lI41fQx+egvgYSIFXI9L2UYufANh6qlv4FalX1sK1sGUw5aNb3b4BnbFieqjZIJNXSrZ+cA96igF2OsAYd+RK2dBxJe9C2egOv1Sq0YzWZEsDBVHMv4RJYfoow46Y+hGsmMWFOVOETvnGFzahyNvtt2T88xctUa7uxYgQ=
matrix:
  allow_failures:
    - rvm: ruby-head
